#!/usr/bin/env bash
if [ ! -f config ]
then
    echo "No config file found, initializing."
    echo "CREATOR_UUID=\"`uuid`\"" >> config
    echo "VENDOR_UUID=\"`uuid`\"" >> config
    read -p "cloud name> " CLOUD_NAME
    echo "CLOUD_NAME=\"$CLOUD_NAME\"" >> config
    read -p "creator name[$CLOUD_NAME]> " CREATOR_NAME
    if [ "x${CREATOR_NAME}x" == "xx" ]
    then
	CREATOR_NAME=$CLOUD_NAME
    fi
    echo "CREATOR_NAME=\"$CREATOR_NAME\"" >> config
    read -p "server> http://" SERVER
    echo "SERVER=\"$SERVER\"" >> config
fi
. config

DATE=`date +%FT%H:%M:%S.0Z`
UUID=`uuid`
SIZE=
SHA=


if [ "x${1}x" == "xx" ]
then
    read -p "zone> " ZONE
else
    ZONE=$1
fi

if [ "x${2}x" == "xx" ]
then
    DFLT=`vmadm get $ZONE | json alias`
    read -p "name[$DFLT]> " NAME
    if [ "x${NAME}x" == xx ]
    then
	NAME=$DFLT
    fi
else
    NAME=$2
fi

if [ "x${3}x" == "xx" ]
then
    read -p "version> " VERSION
else
    VERSION=$3
fi

KIND=`vmadm get $ZONE | json brand`
case $KIND in 
    kvm) 
	ZVOL=`vmadm get $ZONE | json disks[0].zfs_filesystem`
	DISKDRV=`vmadm get $ZONE | json disks[0].model`
	NICDRV=`vmadm get $ZONE | json nics[0].model`
	;;
    joyent)
	ZVOL=`vmadm get 21e0bc5d-af4e-4a44-8137-c7d50870dcbd | json zfs_filesystem`
	;;
    *)
	echo "Only kvm and joyent are supported as brands, '$KIND' is unknown."
	exit 1
	;;
esac

zfs list | grep $ZVOL > /dev/null || exit 1

SNAPSHOT=$ZVOL@$UUID
zfs snapshot $SNAPSHOT || exit 2

VOL_SIZE=`zfs get -pH volsize $ZVOL | awk '{ print $3 }'`
VOL_SIZE=`expr $VOL_SIZE / 1048576`

mkdir -p datasets/$UUID
FILE=datasets/$UUID/$NAME-$VERSION.zvol.gz

echo "Creating zfs archive ($FILE)..."
zfs send $SNAPSHOT | gzip > $FILE || exit 3

SIZE=`ls -l $FILE  | awk '{ print $5 }'`

SHA=`cksum -xsha1 $FILE | awk '{ print $1 }'`

echo "Creating manifest (datasets/$UUID/$UUID.dsmanifest)..."
cat $KIND.dsmanifest.tpl |\
sed -e "s/KIND/$KIND/g" |\
sed -e "s/DISKDRV/$DISKDRV/g" |\
sed -e "s/NICDRV/$NICDRV/g" |\
sed -e "s/CREATOR_UUID/$CREATOR_UUID/g" |\
sed -e "s/VENDOR_UUID/$VENDOR_UUID/g" |\
sed -e "s/UUID/$UUID/g" |\
sed -e "s/CREATOR_NAME/$CREATOR_NAME/g" |\
sed -e "s/VENDOR_NAME/$VENDOR_NAME/g" |\
sed -e "s/CLOUD_NAME/$CLOUD_NAME/g" |\
sed -e "s/NAME/$NAME/g" |\
sed -e "s/VERSION/$VERSION/g" |\
sed -e "s/VOL_SIZE/$VOL_SIZE/g" |\
sed -e "s/SIZE/$SIZE/g" |\
sed -e "s/SHA/$SHA/g" |\
sed -e "s/DATE/$DATE/g" |\
sed -e "s;SERVER;$SERVER;g" > datasets/$UUID/$UUID.dsmanifest

echo Dataset $UUID created.
zfs destroy $SNAPSHOT
